add page tracking to url
openseadragon/bookmark-url pull request #5
Opened 2021-08-25 15:29 UTC by camdey

optional parameter for enabling tracking of the OSD sequence page in the URL, defaults to false:
`viewer.bookmarkUrl({trackPage: true});`

2021-08-26 18:25 UTC, iangilman requested changes
Looks beautiful! Just a couple of comments...

2021-08-26 18:25 UTC, iangilman commented on openseadragon-bookmark-url.js
> +    $.Viewer.prototype.bookmarkUrl = function({trackPage = false} = {}) {
OpenSeadragon still supports IE11, so I think it would be nice if this plugin also did. The default parameters here are part of ES6, and looking at https://kangax.github.io/compat-table/es6/ it looks like IE11 does not support them. Instead I recommend this pattern: 

```
$.Viewer.prototype.bookmarkUrl = function(options) {
  options = options || {};
  var trackPage = options.trackPage || false;
```

2021-08-26 18:25 UTC, iangilman commented on openseadragon-bookmark-url.js
> +            if (trackPage && params.page !== undefined && params.page !== page) {
Since you don't need to do the zoom or pan prior to the `open` in this case, you might as well put the zoom and pan from above into an `else` clause below this.

2021-08-27 12:17 UTC, camdey commented on openseadragon-bookmark-url.js
> +    $.Viewer.prototype.bookmarkUrl = function({trackPage = false} = {}) {
Good point, probably the neater approach if more options were added in the future too!

2021-08-27 12:24 UTC, camdey commented on openseadragon-bookmark-url.js
> +            if (trackPage && params.page !== undefined && params.page !== page) {
👍

2021-08-30 18:25 UTC, iangilman requested changes
Beautiful! 

I'm realizing one more thing that needs doing... this new feature needs to be documented in the README! Can you do that as well?

2021-08-31 09:05 UTC, camdey commented
Done! [Here's a working example](https://artemis-collection.com/showcase/ultra-zoom/#zoom=3.5832&x=0.3974&y=0.2331&id=1115) of a viewer tracking the page with some modifications.

I use the page number to get the URL of the DZI file so I can extract an ID from the string, that way the URL isn't dependent on the order of the DZI files. I've also rounded the zoom/pan values to make the URL a bit cleaner and I use the ID from the DZI to link it to the media titles of the jpg versions of the DZIs in my Wordpress so the title updates with the sequence page.

Wouldn't have been possible without this plugin (or OSD) so thanks for all of your work on those @iangilman 🙏

2021-09-01 18:31 UTC, iangilman approved these changes
Beautiful, thank you! 

Your site looks lovely, BTW!

2021-09-01 18:32 UTC, merged

2021-09-01 18:41 UTC, iangilman commented
I tweaked a few things, I hope you don't mind: https://github.com/openseadragon/bookmark-url/commit/dd1313a517a2dcac848a5681da7803464ef17fee